version: '3.7'

services:
  api-gateway:
    build:
      context: .
      target: development
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - rabbitmq
    command: yarn start:dev api-gateway

  account:
    build:
      context: .
      target: development
      dockerfile: ./apps/account/Dockerfile
    container_name: account
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - mongodb
    command: yarn start:dev account

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./.rabbit-data:/var/lib/rabbitmq
    networks:
      - app-network

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    volumes:
      - ./.mongodb:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
