version: '3'

services:
  nats:
    image: bitnami/nats:latest
    container_name: nats
    env_file: .env
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
